### ISSUE TITLE
Multiple tags for one answer

### ISSUE THREAD

**Issue by ensrationis** [airalab/Aira-0x308d...bfD9#4]
will be great if I will have the opportunity to add multiple tags for one answer like "tag1", "tag2", "tag3": `bla bla bla bla bla bla`

**Comment by vol4tim** [comment]
Implemented in the commit https://github.com/airalab/Aira-0x308d...bfD9/commit/42c4a1a6f7dd868fcf1e2742a1378f13f26af3d0
